spring.application.name=auth-service
spring.datasource.url=jdbc:mysql://localhost:3306/agrilink_auth
spring.datasource.username=root
spring.datasource.password=1234

# --- EMAIL SENDER CONFIGURATION (using Gmail SMTP) ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pnsgauri17@gmail.com
spring.mail.password=rygzvtmoxzotoeqb

# Enable TLS and authentication
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true